baseURL = "https://www.cultivatecuriosity.world/"
languageCode = "en-us"
title = "Cultivate Curiosity"

theme = "newsroom"
copyright = "Copyright © 2020, Juan Orozco; all rights reserved."
canonifyurls = true
paginate = 3
# Enable syntax highlighting
# comment or delete lines 11 ~ 14
pygmentsCodefences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses=true
pygmentsOptions = "linenos=table"

[params]
  imageRoot = "https://res.cloudinary.com/deo07tbou/image/upload/"
  mainSections = ["post"]
